/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/common/alert.vue')['default']
    AudioPlayer: typeof import('./src/components/common/audioPlayer.vue')['default']
    copy: typeof import('./src/components/exam/writingCard copy.vue')['default']
    Counter: typeof import('./src/components/common/counter.vue')['default']
    CounterReverse: typeof import('./src/components/common/counterReverse.vue')['default']
    ExamResult: typeof import('./src/page/examResultPage.vue')['default']
    ExamResult2: typeof import('./src/components/exam/examResult2.vue')['default']
    FloatingPaper: typeof import('./src/components/floating-paper.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    HomeNav: typeof import('./src/components/home-nav.vue')['default']
    ListeningCard: typeof import('./src/components/exam/listeningCard.vue')['default']
    ListeningSingleCard: typeof import('./src/components/exam/listeningSingleCard.vue')['default']
    OptionGroup: typeof import('./src/components/common/optionGroup.vue')['default']
    PagiNation: typeof import('./src/components/pagiNation.vue')['default']
    PaperCard: typeof import('./src/components/paper-card.vue')['default']
    QuestionCarousel: typeof import('./src/components/common/QuestionCarousel.vue')['default']
    QuestionContainer: typeof import('./src/components/common/QuestionContainer.vue')['default']
    Rating: typeof import('./src/components/common/rating.vue')['default']
    ReadingCard: typeof import('./src/components/exam/readingCard.vue')['default']
    ReadingcLozeCard: typeof import('./src/components/exam/readingcLozeCard.vue')['default']
    ReadingmtachCard: typeof import('./src/components/exam/readingmtachCard.vue')['default']
    ReadingreadCard: typeof import('./src/components/exam/readingreadCard.vue')['default']
    RlisteningCard: typeof import('./src/components/examreview/rlisteningCard.vue')['default']
    RlisteningSingleCard: typeof import('./src/components/examreview/rlisteningSingleCard.vue')['default']
    RoptionGroup: typeof import('./src/components/examreview/roptionGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RreadingCard: typeof import('./src/components/examreview/rreadingCard.vue')['default']
    RreadingclozeCard: typeof import('./src/components/examreview/rreadingclozeCard.vue')['default']
    RreadingmatchCard: typeof import('./src/components/examreview/rreadingmatchCard.vue')['default']
    RreadingreadCard: typeof import('./src/components/examreview/rreadingreadCard.vue')['default']
    Translation: typeof import('./src/components/exam/Translation.vue')['default']
    TranslationCard: typeof import('./src/components/exam/TranslationCard.vue')['default']
    WritingCard: typeof import('./src/components/exam/writingCard.vue')['default']
  }
}
