/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./src/components/a.vue')['default']
    FloatingPaper: typeof import('./src/components/floating-paper.vue')['default']
    HomeNav: typeof import('./src/components/home-nav.vue')['default']
    Homepage: typeof import('./src/page/homePage.vue')['default']
    LoginPage: typeof import('./src/page/loginPage.vue')['default']
    PaperCard: typeof import('./src/components/paper-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
