import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import { router } from "./route/router";
import pinia from "./store/index.js";
import { GesturePlugin } from "@vueuse/gesture";
const app = createApp(App);
window.appRouter = router;
app.use(router);
app.use(GesturePlugin);
app.use(pinia);
app.mount("#app");
